### ISSUE TITLE
The github repository name is causing zero discoverability

### ISSUE THREAD

**Issue by ghost** [ironmansoftware/ps-avalonia#2]
Hi,

please take look at the search results: https://github.com/search?q=psavalonia

it dosen't show this repository which might lead people into unmaintained LeXPec project

Please simply remove minus '-' from repository name so this repo can be discovered when using Github internal search.

This might be trivial but exactly because it is trivial you should do it.

**Comment by adamdriscoll** [comment]
Done. Thanks!
